# Generated by Django 3.0.6 on 2020-05-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formy_app', '0003_spreadsheet_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheetfield',
            name='field_type',
            field=models.CharField(choices=[('INTEGER', 'Integer/Number'), ('STRING', 'String/Text Short'), ('AREA', 'String/Text Long'), ('BOOL', 'True/False')], default='STRING', max_length=32),
        ),
    ]
