# Generated by Django 3.0.6 on 2020-06-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formy_app', '0004_auto_20200529_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='track_sub_times',
            field=models.BooleanField(default=True),
        ),
    ]
