# Generated by Django 3.0.7 on 2020-06-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formy_app', '0005_spreadsheet_track_sub_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheetfield',
            name='sort_pos',
            field=models.IntegerField(null=True, verbose_name='Sort Position'),
        ),
    ]
